// Lista predefinisanih tagova

export const predefinedTags = [
    "React",
    "JavaScript",
    "Frontend",
    "Backend",
    "Node.js",
    "TypeScript",
    "CSS",
    "HTML",
    "DevOps",
    "Full Stack",
    "Python",
    "Django",
    "Flask",
    "Java",
    "Spring Boot",
    "C++",
    "C#",
    "Angular",
    "Vue.js",
    "GraphQL",
    "REST API",
    "MongoDB",
    "SQL",
    "PostgreSQL",
    "Docker",
    "Kubernetes",
    "Git",
    "GitHub",
    "Agile",
    "Scrum",
  ];
  